WITH TRIPS as (

select
RIDE_ID,
RIDEABLE_TYPE,
TO_TIMESTAMP(STARTED_AT) AS TRIP_DATE,
start_statio_id as START_STATION_ID,
END_STATION_ID,
MEMBER_CSUAL as MEMBER_CASUAL,
TIMESTAMPDIFF(SECOND,TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS

  from {{ source('demo', 'bike') }} 
  WHERE RIDE_ID != 'ride_id'

)

select 
*
from TRIPS